version: "3.7"

services:
  client:
    container_name: client
    build: ./
    ports:
      - "3000:3000"
    restart: always

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
      - www-html:/var/www/html
      - etc-letsencrypt:/etc/letsencrypt
    depends_on:
      - client
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    depends_on:
      - nginx
    volumes:
      - www-html:/var/www/html
      - etc-letsencrypt:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/html --email avtolikekz@gmail.com  --agree-tos --no-eff-email -d avtolike.kz


volumes:
  www-html:
  etc-letsencrypt: